# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18058e0aa70ebcc1c064a42623acc68ecf36d224e5ae8f6cc6342467170d68cf7166be5f4300d4dc042deea83e669313e5c6946935d93ad6254242725a02fbde

test:
  secret_key_base: e85f6c8e82f7eb5549b2ca2ff96b03bf30cfd60c3f395f8fd87d2b03658ceac925b8c5f51c57065b90287ae9f513dea50a099a4a5b8f9a22253ad2c6bc22f859

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
